apiVersion: v1
kind: Service
metadata:
  name: airbrake-hook
  labels:
    app: airbrake-hook
spec:
  type: NodePort
  ports:
  - port: 3020
    targetPort: 3020
    nodePort: 32003
  selector:
    app: airbrake-hook
